# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proxy.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'proxy.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bproxy.proto\"\xb0\x01\n\x10ProxyUserRequest\x12\x0f\n\x07service\x18\x01 \x01(\t\x12\x0e\n\x06method\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t\x12\x0e\n\x06ticker\x18\x04 \x01(\t\x12\x12\n\nold_ticker\x18\x06 \x01(\t\x12\x12\n\nnew_ticker\x18\x07 \x01(\t\x12\x12\n\nhigh_value\x18\x08 \x01(\x01\x12\x11\n\tlow_value\x18\t \x01(\x01\x12\r\n\x05\x63ount\x18\x05 \x01(\x05\"C\n\x11ProxyUserResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x01\x12\x0f\n\x07\x61verage\x18\x03 \x01(\x01\x32G\n\x0cProxyService\x12\x37\n\x0e\x46orwardRequest\x12\x11.ProxyUserRequest\x1a\x12.ProxyUserResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proxy_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PROXYUSERREQUEST']._serialized_start=16
  _globals['_PROXYUSERREQUEST']._serialized_end=192
  _globals['_PROXYUSERRESPONSE']._serialized_start=194
  _globals['_PROXYUSERRESPONSE']._serialized_end=261
  _globals['_PROXYSERVICE']._serialized_start=263
  _globals['_PROXYSERVICE']._serialized_end=334
# @@protoc_insertion_point(module_scope)
