apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  labels:
    app: auth-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
      - name: auth-service
        image: giovannir24/auth_service_image:latest  # Sostituisci con il nome della tua immagine
        ports:
        - containerPort: 5001  # Porta principale per il gRPC
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  selector:
    app: auth-service
  ports:
  - port: 5001       # Porta del servizio
    targetPort: 5001 # Porta del container