# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: datacollector.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'datacollector.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x64\x61tacollector.proto\"\x07\n\x05\x45mpty\"7\n\x12\x43ollectionResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x11\n\tcollected\x18\x02 \x01(\x05\x32G\n\x14\x44\x61taCollectorService\x12/\n\x10\x43ollectStockData\x12\x06.Empty\x1a\x13.CollectionResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'datacollector_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMPTY']._serialized_start=23
  _globals['_EMPTY']._serialized_end=30
  _globals['_COLLECTIONRESPONSE']._serialized_start=32
  _globals['_COLLECTIONRESPONSE']._serialized_end=87
  _globals['_DATACOLLECTORSERVICE']._serialized_start=89
  _globals['_DATACOLLECTORSERVICE']._serialized_end=160
# @@protoc_insertion_point(module_scope)
