# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: stock.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'stock.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bstock.proto\x12\x05stock\"+\n\nStockQuery\x12\r\n\x05\x65mail\x18\x01 \x01(\t\x12\x0e\n\x06ticker\x18\x02 \x01(\t\"<\n\x0c\x41verageQuery\x12\r\n\x05\x65mail\x18\x01 \x01(\t\x12\x0e\n\x06ticker\x18\x02 \x01(\t\x12\r\n\x05\x63ount\x18\x03 \x01(\x05\".\n\rStockResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x01\"2\n\x0f\x41verageResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0f\n\x07\x61verage\x18\x02 \x01(\x01\x32~\n\x0cStockService\x12\x33\n\x08GetStock\x12\x11.stock.StockQuery\x1a\x14.stock.StockResponse\x12\x39\n\nGetAverage\x12\x13.stock.AverageQuery\x1a\x16.stock.AverageResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'stock_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_STOCKQUERY']._serialized_start=22
  _globals['_STOCKQUERY']._serialized_end=65
  _globals['_AVERAGEQUERY']._serialized_start=67
  _globals['_AVERAGEQUERY']._serialized_end=127
  _globals['_STOCKRESPONSE']._serialized_start=129
  _globals['_STOCKRESPONSE']._serialized_end=175
  _globals['_AVERAGERESPONSE']._serialized_start=177
  _globals['_AVERAGERESPONSE']._serialized_end=227
  _globals['_STOCKSERVICE']._serialized_start=229
  _globals['_STOCKSERVICE']._serialized_end=355
# @@protoc_insertion_point(module_scope)
